---
- hosts: vagrants
  user: vagrant
  become: no
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get --yes install python
      become: yes
  tasks:
    - name: Install base build tools for Yocto
      apt: name={{item}} update_cache=yes
      with_items:
        - gawk
        - wget
        - git-core
        - diffstat
        - unzip
        - texinfo
        - gcc-multilib
        - build-essential
        - chrpath
        - socat
        - libsdl1.2-dev
      become: yes

    - name: Install additional tools for building Firefox 52 on Yocto
      apt: name={{item}} update_cache=yes
      with_items:
        - autoconf2.13
      become: yes

    - name: Install additional tools for building Firefox 60 on Yocto
      apt: name={{item}} update_cache=yes
      with_items:
        - clang
        - llvm
        - clang-3.9
        - llvm-3.9
      become: yes

    - name: Install additional development tools
      apt: name={{item}} update_cache=yes
      with_items:
        - emacs
      become: yes

    - name: Fetch poky
      git:
        repo: git://git.yoctoproject.org/poky
        version: 342fbd6a3e57021c8e28b124b3adb241936f3d9d
        dest: ~/rcar-gen3/poky
        accept_hostkey: yes

    - name: Fetch meta-openembedded
      git:
        repo: git://git.openembedded.org/meta-openembedded
        version: dacfa2b1920e285531bec55cd2f08743390aaf57
        dest: ~/rcar-gen3/meta-openembedded
        accept_hostkey: yes

    - name: Fetch meta-linaro
      git:
        repo: git://git.linaro.org/openembedded/meta-linaro.git
        version: 75dfb67bbb14a70cd47afda9726e2e1c76731885
        dest: ~/rcar-gen3/meta-linaro
        accept_hostkey: yes
        force: yes

    - name: Fetch meta-renesas (R-Car)
      git:
        repo: https://github.com/renesas-rcar/meta-renesas.git
        version: d50e055494cea5de0a348c15ee27cb67a3542e0b
        dest: ~/rcar-gen3/meta-renesas
        accept_hostkey: yes

    - name: Fetch meta-gecko-embedded
      git:
        repo: https://github.com/webdino/meta-gecko-embedded.git
        version: master
        dest: ~/rcar-gen3/meta-gecko-embedded
        accept_hostkey: yes

    - name: Fetch meta-browser
      git:
        repo: https://github.com/webdino/meta-browser.git
        version: firefox-60esr
        dest: ~/rcar-gen3/meta-browser
        accept_hostkey: yes

    - name: Fetch meta-rust
      git:
        repo: https://github.com/webdino/meta-rust.git
        version: jethro-14.0.1_rust_1.24.1
        dest: ~/rcar-gen3/meta-rust
        accept_hostkey: yes

    - name: Make build directory
      file:
        path: ~/rcar-gen3/build/{{item}}
        state: directory
      with_items:
        - conf

    - name: Copy build config files
      copy:
        src: files/conf/{{item}}
        dest: ~/rcar-gen3/build/conf/{{item}}
      with_items:
        - bblayers.conf
        - local.conf
