---
- hosts: vagrants
  user: vagrant
  become: no
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get --yes install python
      become: yes
  tasks:
    - name: Install base build tools for Yocto
      apt: name={{item}} update_cache=yes
      with_items:
        - gawk
        - wget
        - git-core 
        - diffstat
        - unzip
        - texinfo
        - gcc-multilib
        - build-essential
        - chrpath
        - socat
        - libsdl1.2-dev
      become: yes

    - name: Install additional tools for building Firefox 52 on Yocto
      apt: name={{item}} update_cache=yes
      with_items:
        - autoconf2.13
      become: yes

    - name: Install additional tools for building Firefox 60 on Yocto
      apt: name={{item}} update_cache=yes
      with_items:
        - clang
        - llvm
        - clang-3.9
        - llvm-3.9
      become: yes

    - name: Install rust by rustup
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Install rust targets
      shell: ~/.cargo/bin/rustup target add {{ item }}
      with_items:
        - armv7-unknown-linux-gnueabihf

    - name: Fetch poky
      git:
        repo: git://git.yoctoproject.org/poky
        version: 3b223f75eec1738fbc913858e8e11c8305e3edcb
        dest: ~/rzg1-bsp/poky
        accept_hostkey: yes

    - name: Fetch meta-openembedded
      git:
        repo: git://git.openembedded.org/meta-openembedded
        version: dc5634968b270dde250690609f0015f881db81f2
        dest: ~/rzg1-bsp/meta-openembedded
        accept_hostkey: yes

    - name: Fetch meta-linaro
      git:
        repo: git://git.linaro.org/openembedded/meta-linaro.git
        version: 12993e6bc8658ee37d303d8d59007f8dd9ab2b30
        dest: ~/rzg1-bsp/meta-linaro
        accept_hostkey: yes
        force: yes

    - name: Fetch meta-renesas (certified-linux-v2.0.2)
      git:
        repo: https://github.com/renesas-rz/meta-renesas.git
        version: certified-linux-v2.0.2
        dest: ~/rzg1-bsp/meta-renesas
        accept_hostkey: yes

    - name: Fetch meta-gecko-embedded
      git: 
        repo: https://github.com/mozilla-japan/meta-gecko-embedded.git
        version: master
        dest: ~/rzg1-bsp/meta-gecko-embedded
        accept_hostkey: yes

    - name: Fetch meta-browser
      git:
        repo: https://github.com/webdino/meta-browser.git
        version: firefox-60-wip
        dest: ~/rzg1-bsp/meta-browser
        accept_hostkey: yes

    - name: Fix URL of gcc-linaro-4.9
      replace:
        path: ~/rzg1-bsp/meta-linaro/meta-linaro-toolchain/recipes-devtools/gcc/gcc-linaro-4.9.inc
        regexp: 'https:\/\/releases.linaro.org\/\$\{MMYY\}'
        replace: 'https://releases.linaro.org/archive/${MMYY}'
        backup: yes

    - name: Make build directory
      file:
        path: ~/rzg1-bsp/build/{{item}}
        state: directory
      with_items:
        - conf

    - name: Copy build config files
      copy:
        src: files/conf/{{item}}
        dest: ~/rzg1-bsp/build/conf/{{item}}
      with_items:
        - bblayers.conf
        - local.conf
